<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dhcp_app_description'] = 'Приложение DHCP-сервер обеспечивает автоматическую конфигурацию IP устройств в сети.';
$lang['dhcp_app_name'] = 'DHCP Сервер';
$lang['dhcp_authoritative'] = 'Авторитетный';
$lang['dhcp_authoritative_state_invalid'] = 'Авторитетное состояние - инвалид.';
$lang['dhcp_dns'] = 'DNS';
$lang['dhcp_dns_server_invalid'] = 'DNS-сервер является недействительным.';
$lang['dhcp_dns_server_list_invalid'] = 'Список DNS-серверов является недействительным.';
$lang['dhcp_domain'] = 'Домен';
$lang['dhcp_domain_invalid'] = 'Доменное имя является недействительным.';
$lang['dhcp_dynamic'] = 'Динамический';
$lang['dhcp_end_ip_invalid'] = 'Start IP является недействительным.';
$lang['dhcp_expires'] = 'Истекает';
$lang['dhcp_gateway'] = 'Шлюз';
$lang['dhcp_gateway_invalid'] = 'Шлюз является недействительным.';
$lang['dhcp_identifier'] = 'Идентификатор';
$lang['dhcp_ip_range_end'] = 'IP Диапазон конец';
$lang['dhcp_ip_range_invalid'] = 'Диапазон IP является недействительным.';
$lang['dhcp_ip_range_start'] = 'IP Диапазон начало';
$lang['dhcp_lease'] = 'Lease';
$lang['dhcp_lease_time'] = 'Время аренды';
$lang['dhcp_lease_time_invalid'] = 'Lease time is invalid.';
$lang['dhcp_lease_type_invalid'] = 'Lease type is invalid.';
$lang['dhcp_leases'] = 'Leases';
$lang['dhcp_mac_address_already_exists'] = 'MAC адрес уже существует.';
$lang['dhcp_network'] = 'Сеть';
$lang['dhcp_network_interface'] = 'Сетевой интерфейс';
$lang['dhcp_never'] = 'Никогда';
$lang['dhcp_ntp'] = 'NTP';
$lang['dhcp_ntp_server_invalid'] = 'Сервер NTP является недействительным.';
$lang['dhcp_start_ip_invalid'] = 'Start IP является недействительным.';
$lang['dhcp_state_invalid'] = 'Start IP является недействительным.';
$lang['dhcp_static'] = 'Статический';
$lang['dhcp_static_lease'] = 'Аренда статического';
$lang['dhcp_subnet'] = 'Подсеть';
$lang['dhcp_subnets'] = 'Подсетей';
$lang['dhcp_tftp'] = 'TFTP';
$lang['dhcp_tftp_server_invalid'] = 'Сервер TFTP является недействительным.';
$lang['dhcp_vendor'] = 'Производитель';
$lang['dhcp_wins'] = 'WINS';
$lang['dhcp_wins_server_invalid'] = 'WINS-сервер является недействительным.';
$lang['dhcp_wpad'] = 'WPAD';
$lang['dhcp_wpad_server_invalid'] = 'WPAD сервера неверный (eg. http://wpad.example.com/wpad.dat).';
