#!/bin/sh

# Add sudo entry
#---------------

/usr/sbin/addsudo /usr/sbin/dhcptest app-dhcp-core

# Initialize domain name with default
#------------------------------------

/usr/clearos/app/dhcp/deploy/initialize
