<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dhcp_app_description'] = 'DHCP-servern ger automatiskt en IP-konfiguration till enheter på ditt nätverk.';
$lang['dhcp_app_name'] = 'DHCP-server';
$lang['dhcp_authoritative'] = 'Auktoritativ';
$lang['dhcp_authoritative_state_invalid'] = 'Auktoritativa statusen är ogiltig.';
$lang['dhcp_dhcp'] = 'DHCP';
$lang['dhcp_dns'] = 'DNS';
$lang['dhcp_dns_server_invalid'] = 'DNS-server är ogiltig.';
$lang['dhcp_dns_server_list_invalid'] = 'Listan över DNS-servrar är ogiltig.';
$lang['dhcp_domain'] = 'Domän';
$lang['dhcp_domain_invalid'] = 'Domännamnet är ogiltigt.';
$lang['dhcp_dynamic'] = 'Dynamisk';
$lang['dhcp_end_ip_invalid'] = 'Övre gräns för IP är ogiltigt.';
$lang['dhcp_expires'] = 'Går ut';
$lang['dhcp_gateway'] = 'Gateway';
$lang['dhcp_gateway_invalid'] = 'Gateway är ogiltig.';
$lang['dhcp_identifier'] = 'Identifierare';
$lang['dhcp_ip_range_end'] = 'Övre gräns för IP-området';
$lang['dhcp_ip_range_invalid'] = 'IP-området är ogiltigt.';
$lang['dhcp_ip_range_start'] = 'Undre gräns för IP-området';
$lang['dhcp_lease'] = 'Lån';
$lang['dhcp_lease_time'] = 'Lånetid';
$lang['dhcp_lease_time_invalid'] = 'Lånetiden är ogiltig.';
$lang['dhcp_lease_type_invalid'] = 'Lånetyp är ogiltig.';
$lang['dhcp_leases'] = 'Lån';
$lang['dhcp_mac_address_already_exists'] = 'MAC-adressen finns redan.';
$lang['dhcp_network'] = 'Nätverk';
$lang['dhcp_network_interface'] = 'Nätverkskort';
$lang['dhcp_never'] = 'Aldrig';
$lang['dhcp_ntp'] = 'NTP';
$lang['dhcp_ntp_server_invalid'] = 'NTP-servern är ogiltig.';
$lang['dhcp_start_ip_invalid'] = 'Undre gräns för IP är ogiltigt.';
$lang['dhcp_state_invalid'] = 'Status är ogiltig.';
$lang['dhcp_static'] = 'Statisk';
$lang['dhcp_static_lease'] = 'Statiskt lån';
$lang['dhcp_subnet'] = 'Subnät';
$lang['dhcp_subnets'] = 'Subnät';
$lang['dhcp_tftp'] = 'TFTP';
$lang['dhcp_tftp_server_invalid'] = 'TFTP-servern är ogiltig.';
$lang['dhcp_vendor'] = 'Tillverkare';
$lang['dhcp_wins'] = 'WINS';
$lang['dhcp_wins_server_invalid'] = 'WINS-servern är ogiltig.';
$lang['dhcp_wpad'] = 'WPAD';
$lang['dhcp_wpad_server_invalid'] = 'WPAD server is invalid (eg. http://wpad.example.com/wpad.dat).';
