<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dhcp_app_description'] = 'Aplikacja serwera DHCP dostarcza automatyczną konfigurację adresów IP dla urządzeń w Twojej sieci.';
$lang['dhcp_app_name'] = 'Serwer DHCP';
$lang['dhcp_authoritative'] = 'Autorytatywny';
$lang['dhcp_authoritative_state_invalid'] = 'Status autorytatywności jest nieprawidłowy.';
$lang['dhcp_dns'] = 'DNS';
$lang['dhcp_dns_server_invalid'] = 'Podany serwer DNS jest nieprawidłowy.';
$lang['dhcp_dns_server_list_invalid'] = 'Podana lista serwerów DNS jest nieprawidłowa.';
$lang['dhcp_domain'] = 'Domena';
$lang['dhcp_domain_invalid'] = 'Podana nazwa domenowa jest nieprawidłowa.';
$lang['dhcp_dynamic'] = 'Dynamiczna';
$lang['dhcp_end_ip_invalid'] = 'Podany końcowy adres IP jest nieprawidłowy.';
$lang['dhcp_expires'] = 'Wygasa';
$lang['dhcp_gateway'] = 'Brama sieciowa';
$lang['dhcp_gateway_invalid'] = 'Podana brama sieciowa jest nieprawidłowa.';
$lang['dhcp_identifier'] = 'Identyfikator';
$lang['dhcp_ip_range_end'] = 'Koniec zakresu adresów IP';
$lang['dhcp_ip_range_invalid'] = 'Podany zakres IP jest nieprawidłowy.';
$lang['dhcp_ip_range_start'] = 'Początek zakresu adresów IP';
$lang['dhcp_lease'] = 'Dzierżawa';
$lang['dhcp_lease_time'] = 'Czas dzierżawy';
$lang['dhcp_lease_time_invalid'] = 'Podany czas dzierżawy jest nieprawidłowy.';
$lang['dhcp_lease_type_invalid'] = 'Podany czas dzierżawy jest nieprawidłowy.';
$lang['dhcp_leases'] = 'Dzierżawy';
$lang['dhcp_mac_address_already_exists'] = 'Podany adres MAC już istnieje.';
$lang['dhcp_network'] = 'Sieć';
$lang['dhcp_network_interface'] = 'Interfejs sieciowy';
$lang['dhcp_never'] = 'Nigdy';
$lang['dhcp_ntp'] = 'NTP';
$lang['dhcp_ntp_server_invalid'] = 'Podany serwer NTP jest nieprawidłowy.';
$lang['dhcp_start_ip_invalid'] = 'Podany początkowy adres IP jest nieprawidłowy.';
$lang['dhcp_state_invalid'] = 'Status jest nieprawidłowy.';
$lang['dhcp_static'] = 'Statyczna';
$lang['dhcp_static_lease'] = 'Dzierżawa statyczna';
$lang['dhcp_subnet'] = 'Podsieć';
$lang['dhcp_subnets'] = 'Podsieci';
$lang['dhcp_tftp'] = 'TFTP';
$lang['dhcp_tftp_server_invalid'] = 'Podany serwer TFTP jest nieprawidłowy.';
$lang['dhcp_vendor'] = 'Producent';
$lang['dhcp_wins'] = 'WINS';
$lang['dhcp_wins_server_invalid'] = 'Podany serwer WINS jest nieprawidłowy';
